project_id          = "project-0209a452-648a-426d-a7b"
region              = "europe-west9"
zone                = "europe-west9-b"
ssh_username        = "ubuntu"
ssh_public_key_file = "~/.ssh/id_rsa.pub"
