---
# Playbook principal d'orchestration pour le Cluster Kubernetes K3s

- name: Configuration commune de base sur tous les nœuds
  import_playbook: common.yml

- name: Configuration et déploiement du nœud Master (Control Plane)
  import_playbook: master.yml

- name: Configuration et déploiement des nœuds Workers (Agents)
  import_playbook: worker.yml

- name: Dédier le nœud monitoring (label + taint)
  import_playbook: monitoring.yml

- name: Déploiement et configuration d'Apache Spark
  import_playbook: spark.yml

- name: Déploiement d'un cluster HDFS distribué (NameNode + DataNodes)
  import_playbook: hdfs.yml

