# Fichier généré automatiquement par Terraform / OpenTofu. Ne pas modifier manuellement.

[masters]
k8s-master ansible_host=34.155.44.181 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
k8s-worker-1 ansible_host=34.155.110.32 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
k8s-worker-2 ansible_host=34.163.196.218 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k8s:children]
masters
workers
